In [23]:
import torch
import torch.utils.dlpack
import open3d as o3d
import numpy as np

## Tensor creation

In [2]:
# From list
a = o3d.Tensor([0, 1, 2])
print(a)

# Dtype inferred from list
a_float = o3d.Tensor([0.0, 1.0, 2.0])
print(a_float)

# From Numpy
a = o3d.Tensor(np.array([0, 1, 2]))
print(a)

# Specify dtype
a = o3d.Tensor(np.array([0, 1, 2]), dtype=o3d.Dtype.Float64)
print(a)

# Specify device
# Specify dtype
a = o3d.Tensor(np.array([0, 1, 2]), device=o3d.Device("CUDA:0"))
print(a)

[0 1 2]
Tensor[shape={3}, stride={1}, Int64, CPU:0, 0x555edab0e130]
[0 1 2]
Tensor[shape={3}, stride={1}, Float64, CPU:0, 0x555edab0e6a0]
[0 1 2]
Tensor[shape={3}, stride={1}, Int64, CPU:0, 0x555edab0e7a0]
[0 1 2]
Tensor[shape={3}, stride={1}, Float64, CPU:0, 0x555edab0e880]
[0 1 2]
Tensor[shape={3}, stride={1}, Int64, CUDA:0, 0x7f2eaf200000]


## Properties of a tensor

In [3]:
vals = np.array((range(24))).reshape(2, 3, 4)
a = o3d.Tensor(np.array(vals), 
               dtype=o3d.Dtype.Float64,
               device=o3d.Device("CUDA:0"))
print(f"a.shape: {a.shape}")
print(f"a.strides: {a.strides}")
print(f"a.dtype: {a.dtype}")
print(f"a.device: {a.device}")
print(f"a.ndim: {a.ndim}")

a.shape: {2, 3, 4}
a.strides: {12, 4, 1}
a.dtype: Dtype.Float64
a.device: CUDA:0
a.ndim: 3


## Copy & device transfer

In [4]:
# Host -> Device
a_cpu = o3d.Tensor([0, 1, 2])
a_gpu = a_cpu.cuda(0)
print(a_gpu)

# Device -> Device
a_gpu = o3d.Tensor([0, 1, 2], device=o3d.Device("CUDA:0"))
a_cpu = a_gpu.cpu()
print(a_cpu)

# Device -> Host
a_gpu_0 = o3d.Tensor([0, 1, 2], device=o3d.Device("CUDA:0"))
a_gpu_1 = a_gpu_0.cuda(1)
print(a_gpu_1)

[0 1 2]
Tensor[shape={3}, stride={1}, Int64, CUDA:0, 0x7f2eaf200000]
[0 1 2]
Tensor[shape={3}, stride={1}, Int64, CPU:0, 0x555edb601b80]
[0 1 2]
Tensor[shape={3}, stride={1}, Int64, CUDA:1, 0x7f2e9f200000]


## Type casting

In [5]:
# E.g. float -> int
a = o3d.Tensor([0.1, 1.5, 2.7])
b = a.to(o3d.Dtype.Int32)
print(a)
print(b)

[0.1 1.5 2.7]
Tensor[shape={3}, stride={1}, Float64, CPU:0, 0x555edb8b2b50]
[0 1 2]
Tensor[shape={3}, stride={1}, Int32, CPU:0, 0x555edb806fb0]


## Numpy I/O with direct memory map

In [13]:
# From numpy
np_a = np.ones((5,), dtype=np.int32)
o3_a = o3d.Tensor.from_numpy(np_a)

# Changes to numpy array reflects on open3d Tensor and vice versa
np_a[0] = 100
o3_a[1] = 200
print(np_a)
print(o3_a)

[100 200   1   1   1]
[100 200 1 1 1]
Tensor[shape={5}, stride={1}, Int32, CPU:0, 0x555edb5fe6e0]


In [28]:
# To numpy
o3_a = o3d.Tensor([1, 1, 1, 1, 1], dtype=o3d.Dtype.Int32)
np_a = o3_a.numpy()

# Changes to numpy array reflects on open3d Tensor and vice versa
np_a[0] = 100
o3_a[1] = 200
print(f"np_a: {np_a}")
print(f"o3_a: {o3_a}")

# For CUDA Tensor, call cpu() before calling numpy()
o3_a = o3d.Tensor([1, 1, 1, 1, 1], device=o3d.Device("CUDA:0"))
print(f"o3_a.cpu().numpy(): {o3_a.cpu().numpy()}")

np_a: [100 200   1   1   1]
o3_a: [100 200 1 1 1]
Tensor[shape={5}, stride={1}, Int32, CPU:0, 0x555edb4fa000]

o3_a.cpu().numpy(): [1 1 1 1 1]


## PyTorch I/O with DLPack memory map

In [27]:
# From PyTorch
th_a = torch.ones((5,))
o3_a = o3d.Tensor.from_dlpack(torch.utils.dlpack.to_dlpack(th_a))
print(f"th_a: {th_a}")
print(f"o3_a: {o3_a}")
print("")

# Changes to PyTorch array reflects on open3d Tensor and vice versa

th_a: tensor([1., 1., 1., 1., 1.])
o3_a: [1 1 1 1 1]
Tensor[shape={5}, stride={1}, Float32, CPU:0, 0x555edb4fb280]



## 

## 

## 

## 

In [7]:
## 